package PedidoApp;


/**
* PedidoApp/Pedido.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pedido.idl
* sábado 3 de noviembre de 2018 11:41:46 AM COT
*/

public interface Pedido extends PedidoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Pedido
