package PedidoApp;

/**
* PedidoApp/PedidoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pedido.idl
* sabado 3 de noviembre de 2018 11:41:46 AM COT
*/

public final class PedidoHolder implements org.omg.CORBA.portable.Streamable
{
  public PedidoApp.Pedido value = null;

  public PedidoHolder ()
  {
  }

  public PedidoHolder (PedidoApp.Pedido initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PedidoApp.PedidoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PedidoApp.PedidoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PedidoApp.PedidoHelper.type ();
  }

}
