package PedidoApp;


/**
* PedidoApp/PedidoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pedido.idl
* sabado 3 de noviembre de 2018 11:41:46 AM COT
*/

public interface PedidoOperations 
{
  boolean guardarPedido (int id_pedido, String fecha, String cantidad_producto, String precio_unitario);
  boolean actualizarPedido (int id_pedido, String fecha, String cantidad_producto, String precio_unitario);
  boolean eliminarPedido (int id_pedido);
  String consultarPedido (int id_pedido);
  void shoutdown ();
} // interface PedidoOperations
