package ClienteApp;


/**
* ClienteApp/_ClienteStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* viernes 2 de noviembre de 2018 11:25:11 AM COT
*/

public class _ClienteStub extends org.omg.CORBA.portable.ObjectImpl implements ClienteApp.Cliente
{

  public boolean guardarCliente (int id_cliente, String nombres, String apellidos, String numero_identificacion, String genero, String telefono, String ciudad)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guardarCliente", true);
                $out.write_long (id_cliente);
                $out.write_wstring (nombres);
                $out.write_wstring (apellidos);
                $out.write_wstring (numero_identificacion);
                $out.write_wstring (genero);
                $out.write_wstring (telefono);
                $out.write_wstring (ciudad);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guardarCliente (id_cliente, nombres, apellidos, numero_identificacion, genero, telefono, ciudad        );
            } finally {
                _releaseReply ($in);
            }
  } // guardarCliente

  public boolean actualizarCliente (int id_cliente, String nombres, String apellidos, String numero_identificacion, String genero, String telefono, String ciudad)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarCliente", true);
                $out.write_long (id_cliente);
                $out.write_wstring (nombres);
                $out.write_wstring (apellidos);
                $out.write_wstring (numero_identificacion);
                $out.write_wstring (genero);
                $out.write_wstring (telefono);
                $out.write_wstring (ciudad);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarCliente (id_cliente, nombres, apellidos, numero_identificacion, genero, telefono, ciudad        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarCliente

  public boolean eliminarCliente (int id_cliente)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarCliente", true);
                $out.write_long (id_cliente);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarCliente (id_cliente        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarCliente

  public String consultarCliente (int id_cliente)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarCliente", true);
                $out.write_long (id_cliente);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarCliente (id_cliente        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarCliente

  public void shoutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shoutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shoutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shoutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClienteApp/Cliente:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ClienteStub
