package ClienteApp;


/**
* ClienteApp/ClientePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* viernes 2 de noviembre de 2018 11:25:11 AM COT
*/

public abstract class ClientePOA extends org.omg.PortableServer.Servant
 implements ClienteApp.ClienteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("guardarCliente", new java.lang.Integer (0));
    _methods.put ("actualizarCliente", new java.lang.Integer (1));
    _methods.put ("eliminarCliente", new java.lang.Integer (2));
    _methods.put ("consultarCliente", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClienteApp/Cliente/guardarCliente
       {
         int id_cliente = in.read_long ();
         String nombres = in.read_wstring ();
         String apellidos = in.read_wstring ();
         String numero_identificacion = in.read_wstring ();
         String genero = in.read_wstring ();
         String telefono = in.read_wstring ();
         String ciudad = in.read_wstring ();
         boolean $result = false;
         $result = this.guardarCliente (id_cliente, nombres, apellidos, numero_identificacion, genero, telefono, ciudad);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ClienteApp/Cliente/actualizarCliente
       {
         int id_cliente = in.read_long ();
         String nombres = in.read_wstring ();
         String apellidos = in.read_wstring ();
         String numero_identificacion = in.read_wstring ();
         String genero = in.read_wstring ();
         String telefono = in.read_wstring ();
         String ciudad = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarCliente (id_cliente, nombres, apellidos, numero_identificacion, genero, telefono, ciudad);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ClienteApp/Cliente/eliminarCliente
       {
         int id_cliente = in.read_long ();
         boolean $result = false;
         $result = this.eliminarCliente (id_cliente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // ClienteApp/Cliente/consultarCliente
       {
         int id_cliente = in.read_long ();
         String $result = null;
         $result = this.consultarCliente (id_cliente);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // ClienteApp/Cliente/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClienteApp/Cliente:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Cliente _this() 
  {
    return ClienteHelper.narrow(
    super._this_object());
  }

  public Cliente _this(org.omg.CORBA.ORB orb) 
  {
    return ClienteHelper.narrow(
    super._this_object(orb));
  }


} // class ClientePOA
