package AlmacenApp;


/**
* AlmacenApp/_AlmacenStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Almacen.idl
* miércoles 7 de noviembre de 2018 09:31:40 PM COT
*/

public class _AlmacenStub extends org.omg.CORBA.portable.ObjectImpl implements AlmacenApp.Almacen
{

  public boolean guardarAlmacen (int id_almacen, String nombre, String telefono, String direccion, String ciudad)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guardarAlmacen", true);
                $out.write_long (id_almacen);
                $out.write_wstring (nombre);
                $out.write_wstring (telefono);
                $out.write_wstring (direccion);
                $out.write_wstring (ciudad);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guardarAlmacen (id_almacen, nombre, telefono, direccion, ciudad        );
            } finally {
                _releaseReply ($in);
            }
  } // guardarAlmacen

  public boolean actualizarAlmacen (int id_almacen, String nombre, String telefono, String direccion, String ciudad)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarAlmacen", true);
                $out.write_long (id_almacen);
                $out.write_wstring (nombre);
                $out.write_wstring (telefono);
                $out.write_wstring (direccion);
                $out.write_wstring (ciudad);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarAlmacen (id_almacen, nombre, telefono, direccion, ciudad        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarAlmacen

  public boolean eliminarAlmacen (int id_almacen)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarAlmacen", true);
                $out.write_long (id_almacen);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarAlmacen (id_almacen        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarAlmacen

  public String consultarAlmacen (int id_almacen)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarAlmacen", true);
                $out.write_long (id_almacen);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarAlmacen (id_almacen        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarAlmacen

  public void shoutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shoutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shoutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shoutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AlmacenApp/Almacen:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AlmacenStub
