package AlmacenApp;


/**
* AlmacenApp/AlmacenHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Almacen.idl
* miércoles 7 de noviembre de 2018 09:31:40 PM COT
*/

abstract public class AlmacenHelper
{
  private static String  _id = "IDL:AlmacenApp/Almacen:1.0";

  public static void insert (org.omg.CORBA.Any a, AlmacenApp.Almacen that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AlmacenApp.Almacen extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AlmacenApp.AlmacenHelper.id (), "Almacen");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AlmacenApp.Almacen read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AlmacenStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AlmacenApp.Almacen value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AlmacenApp.Almacen narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AlmacenApp.Almacen)
      return (AlmacenApp.Almacen)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AlmacenApp._AlmacenStub stub = new AlmacenApp._AlmacenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AlmacenApp.Almacen unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AlmacenApp.Almacen)
      return (AlmacenApp.Almacen)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AlmacenApp._AlmacenStub stub = new AlmacenApp._AlmacenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
