package AlmacenApp;

/**
* AlmacenApp/AlmacenHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Almacen.idl
* miercoles 7 de noviembre de 2018 09:31:40 PM COT
*/

public final class AlmacenHolder implements org.omg.CORBA.portable.Streamable
{
  public AlmacenApp.Almacen value = null;

  public AlmacenHolder ()
  {
  }

  public AlmacenHolder (AlmacenApp.Almacen initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AlmacenApp.AlmacenHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AlmacenApp.AlmacenHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AlmacenApp.AlmacenHelper.type ();
  }

}
