package AlmacenApp;


/**
* AlmacenApp/Almacen.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Almacen.idl
* miercoles 7 de noviembre de 2018 09:31:40 PM COT
*/

public interface Almacen extends AlmacenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Almacen
