package AlmacenApp;


/**
* AlmacenApp/AlmacenPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Almacen.idl
* miércoles 7 de noviembre de 2018 09:31:40 PM COT
*/

public abstract class AlmacenPOA extends org.omg.PortableServer.Servant
 implements AlmacenApp.AlmacenOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("guardarAlmacen", new java.lang.Integer (0));
    _methods.put ("actualizarAlmacen", new java.lang.Integer (1));
    _methods.put ("eliminarAlmacen", new java.lang.Integer (2));
    _methods.put ("consultarAlmacen", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AlmacenApp/Almacen/guardarAlmacen
       {
         int id_almacen = in.read_long ();
         String nombre = in.read_wstring ();
         String telefono = in.read_wstring ();
         String direccion = in.read_wstring ();
         String ciudad = in.read_wstring ();
         boolean $result = false;
         $result = this.guardarAlmacen (id_almacen, nombre, telefono, direccion, ciudad);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // AlmacenApp/Almacen/actualizarAlmacen
       {
         int id_almacen = in.read_long ();
         String nombre = in.read_wstring ();
         String telefono = in.read_wstring ();
         String direccion = in.read_wstring ();
         String ciudad = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarAlmacen (id_almacen, nombre, telefono, direccion, ciudad);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // AlmacenApp/Almacen/eliminarAlmacen
       {
         int id_almacen = in.read_long ();
         boolean $result = false;
         $result = this.eliminarAlmacen (id_almacen);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // AlmacenApp/Almacen/consultarAlmacen
       {
         int id_almacen = in.read_long ();
         String $result = null;
         $result = this.consultarAlmacen (id_almacen);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // AlmacenApp/Almacen/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AlmacenApp/Almacen:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Almacen _this() 
  {
    return AlmacenHelper.narrow(
    super._this_object());
  }

  public Almacen _this(org.omg.CORBA.ORB orb) 
  {
    return AlmacenHelper.narrow(
    super._this_object(orb));
  }


} // class AlmacenPOA
