package ProductoApp;

/**
* ProductoApp/ProductoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* jueves 1 de noviembre de 2018 02:31:04 PM COT
*/

public final class ProductoHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductoApp.Producto value = null;

  public ProductoHolder ()
  {
  }

  public ProductoHolder (ProductoApp.Producto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductoApp.ProductoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductoApp.ProductoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductoApp.ProductoHelper.type ();
  }

}
