package ProductoApp;


/**
* ProductoApp/ProductoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Producto.idl
* jueves 1 de noviembre de 2018 02:31:04 PM COT
*/

public interface ProductoOperations 
{
  boolean guardarProducto (int id_producto, String descripcion, String cantidad_producto, String precio);
  boolean actualizarProducto (int id_producto, String descripcion, String cantidad_producto, String precio);
  boolean eliminarProducto (int id_producto);
  String consultarProducto (int id_producto);
  void shoutdown ();
} // interface ProductoOperations
