package FacturaApp;


/**
* FacturaApp/FacturaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factura.idl
* miercoles 14 de noviembre de 2018 09:27:39 AM COT
*/

public abstract class FacturaPOA extends org.omg.PortableServer.Servant
 implements FacturaApp.FacturaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("guardarFactura", new java.lang.Integer (0));
    _methods.put ("actualizarFactura", new java.lang.Integer (1));
    _methods.put ("eliminarFactura", new java.lang.Integer (2));
    _methods.put ("consultarFactura", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FacturaApp/Factura/guardarFactura
       {
         int id_factura = in.read_long ();
         String id_pedido = in.read_wstring ();
         String id_cliente = in.read_wstring ();
         String id_producto = in.read_wstring ();
         String id_almacen = in.read_wstring ();
         String fecha = in.read_wstring ();
         String detalle_factura = in.read_wstring ();
         String ciudad = in.read_wstring ();
         String cantidad_ordenada = in.read_wstring ();
         String valor_venta = in.read_wstring ();
         boolean $result = false;
         $result = this.guardarFactura (id_factura, id_pedido, id_cliente, id_producto, id_almacen, fecha, detalle_factura, ciudad, cantidad_ordenada, valor_venta);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // FacturaApp/Factura/actualizarFactura
       {
         int id_factura = in.read_long ();
         String id_pedido = in.read_wstring ();
         String id_cliente = in.read_wstring ();
         String id_producto = in.read_wstring ();
         String id_almacen = in.read_wstring ();
         String fecha = in.read_wstring ();
         String detalle_factura = in.read_wstring ();
         String ciudad = in.read_wstring ();
         String cantidad_ordenada = in.read_wstring ();
         String valor_venta = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarFactura (id_factura, id_pedido, id_cliente, id_producto, id_almacen, fecha, detalle_factura, ciudad, cantidad_ordenada, valor_venta);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // FacturaApp/Factura/eliminarFactura
       {
         int id_factura = in.read_long ();
         boolean $result = false;
         $result = this.eliminarFactura (id_factura);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // FacturaApp/Factura/consultarFactura
       {
         int id_factura = in.read_long ();
         String $result = null;
         $result = this.consultarFactura (id_factura);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // FacturaApp/Factura/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FacturaApp/Factura:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Factura _this() 
  {
    return FacturaHelper.narrow(
    super._this_object());
  }

  public Factura _this(org.omg.CORBA.ORB orb) 
  {
    return FacturaHelper.narrow(
    super._this_object(orb));
  }


} // class FacturaPOA
