package FacturaApp;


/**
* FacturaApp/FacturaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factura.idl
* miercoles 14 de noviembre de 2018 09:27:39 AM COT
*/

public interface FacturaOperations 
{
  boolean guardarFactura (int id_factura, String id_pedido, String id_cliente, String id_producto, String id_almacen, String fecha, String detalle_factura, String ciudad, String cantidad_ordenada, String valor_venta);
  boolean actualizarFactura (int id_factura, String id_pedido, String id_cliente, String id_producto, String id_almacen, String fecha, String detalle_factura, String ciudad, String cantidad_ordenada, String valor_venta);
  boolean eliminarFactura (int id_factura);
  String consultarFactura (int id_factura);
  void shoutdown ();
} // interface FacturaOperations
